# 主配置文件
server:
  port: 8080
  tomcat:
    max-http-form-post-size: -1
  servlet:
    session:
      # 配置会话超时
      timeout: 120s

# 文件上传路径
web:
  upload-path: /data/

spring:
  datasource:
    url: jdbc:mysql://43.138.144.174:3306/image_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: ncu509509
    password: 509ncu905   #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 300MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/META-INF/resources/webjars/,file:${web.upload-path}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: 127.0.0.1
    port: 6379

# 是否执行MyBatis xml配置文件的状态检查, 只是检查状态,默认false
mybatis:
  check-config-location: true
# mybatis-config.xml文件的位置
  config-location: classpath:/mybatis-config.xml
# Mapper对应的xml路径
  mapper-locations: classpath:/mapper/*.xml
# 设置别名的路径,可避免写全限定类名
#  type-aliases-package: com.manu.mybatisxml.model

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

logging:
  level:
    root: info

model:
  url: http://localhost:8085

token:
  access-token-effective-second: 300     # token有效时间，单位秒
  refresh-token-effective-second: 600